---
- name: Deploy HTML app with Docker
  hosts: webserver
  become: yes

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      shell: docker pull nini117/html-docker-app

    - name: Run container
      shell: docker run -d -p 80:80 --name htmlapp --rm nini117/html-docker-app
      ignore_errors: yes
