---
- name: Deploy HTML app with Docker
  hosts: webserver
  become: yes

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop and remove any existing container
      shell: docker rm -f htmlapp || true

    - name: Pull latest Docker image
      shell: docker pull nini117/html-docker-app

    - name: Run new container
      shell: docker run -d -p 80:80 --name htmlapp nini117/html-docker-app
